$kind: http-example
request:
  url: http://localhost:3000/v1/roles/user/{{userId}}
  method: GET
  headers:
    Authorization: Bearer <access_token>
  pathVariables:
    userId: uuid-of-user
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: |-
      {
        "success": true,
        "message": "OK",
        "data": [
          {
            "id": "uuid-of-user-role",
            "user_id": "uuid-of-user",
            "role_id": "uuid-of-role",
            "assigned_by": null,
            "created_at": "2026-06-30T10:00:00.000Z",
            "role": {
              "id": "uuid-of-role",
              "name": "admin",
              "created_at": "2026-06-30T10:00:00.000Z"
            }
          }
        ]
      }
order: 1000
