$kind: http-request
description: Returns all roles assigned to a specific user. Requires view_roles permission.
url: http://localhost:3000/roles/user/{{userId}}
method: GET
headers:
  Authorization: Bearer <access_token>
examples: ./.resources/Get User's Roles.resources/examples
order: 3000
