$kind: http-example
request:
  url: http://localhost:3000/v1/roles
  method: GET
  headers:
    Authorization: Bearer <access_token>
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: |-
      {
        "success": true,
        "message": "OK",
        "data": [
          {
            "id": "uuid-of-role",
            "name": "admin",
            "created_at": "2026-06-30T10:00:00.000Z",
            "role_permissions": [
              {
                "id": "uuid-of-rp",
                "role_id": "uuid-of-role",
                "permission_id": "uuid-of-permission",
                "permission": {
                  "id": "uuid-of-permission",
                  "name": "view_roles",
                  "created_at": "2026-06-30T10:00:00.000Z"
                }
              }
            ]
          }
        ]
      }
order: 1000
